defaults:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  run:
    dir: .
  output_subdir: null

data:
  dataset: Cora
  target_ratio: 0.5
  perturb_rate: 0
  neg_sample_ratio: 1.0
  batch_size: 1

model:
  out_channels: 32
  layer_type: GATConv
  use_edge_for_predict: full

train:
  num_epochs: 1000
  learning_rate: 0.005
  regularization: 0

model_path: model
results: results/results.json
seed: 38